name: Deploy Firebase

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'firebase-admin/**'
      - '.github/workflows/deploy-firebase.yml'

jobs:
  deploy-firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Set environment variables
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      - name: Install Firebase dependencies
        working-directory: firebase-admin
        run: npm ci

      # - name: Test Firestore rules (emulator)
      #   working-directory: firebase-admin
      #   run: npm run test:rules:emulator
      
# Note: The above test is currently failing due to the firebase-tools dependency on Java 21, which is not available in the GitHub Actions environment. Once this is resolved, we can re-enable the test to ensure our Firestore rules are properly tested in the CI environment.     
# > test:rules:emulator
# > RULES_TARGET=emulator firebase emulators:exec --only auth,firestore 'node --test tests/firestore.rules.test.mjs'

# (node:2386) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
# (Use `node --trace-deprecation ...` to show where the warning was created)
# ⚠  emulators: You are not currently authenticated so some features may not work correctly. Please run firebase login to authenticate the CLI.
# i  emulators: Shutting down emulators.

# Error: firebase-tools no longer supports Java version before 21. Please install a JDK at version 21 or above to get a compatible runtime.
# Error: Process completed with exit code 1.


      - name: Deploy Firebase
        working-directory: firebase-admin
        run: npm run deploy:ci -- --token ${{ secrets.FIREBASE_TOKEN }}
