name: Build and Deploy Firebase

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Set environment
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "VITE_ENV=prod" >> $GITHUB_ENV
            echo "basename=retro-collections" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
            echo "VITE_ENV=dev" >> $GITHUB_ENV
            echo "basename=retro-collections-develop" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        working-directory: retro-collections-web
        run: npm ci

      - name: Build frontend
        working-directory: retro-collections-web
        run: |
          BASE_PATH="/${{ env.basename }}/" npm run build

      - name: Deploy Firebase (FULL)
        run: |
          npm run deploy:ci -- --token ${{ secrets.FIREBASE_TOKEN }}